import type { SeedRepo } from "../types";

const rows: Array<[string, string[]]> = [
  ["git/git", ["version_control", "command_routing", "storage_boundary", "compatibility"]],
  ["pytest-dev/pytest", ["plugin_hooks", "fixture_system", "testing_extension", "error_reporting"]],
  ["fastify/fastify", ["plugin_architecture", "schema_validation", "lifecycle_hooks", "framework_boundary"]],
  ["kubernetes/kubernetes", ["controller_pattern", "reconciliation_loop", "api_boundary", "declarative_state"]],
  ["temporalio/temporal", ["durable_workflow", "retry_policy", "checkpointing", "task_state_machine"]],
  ["open-telemetry/opentelemetry-collector", ["receiver_processor_exporter", "plugin_pipeline", "configuration_driven_architecture"]],
  ["prometheus/prometheus", ["timeseries_ingest", "query_engine", "pull_model", "storage_boundary"]],
  ["grafana/grafana", ["plugin_system", "dashboard_model", "datasource_abstraction", "frontend_backend_boundary"]],
  ["astral-sh/uv", ["fast_cli", "resolver", "cache", "python_project_workflow"]],
  ["astral-sh/ruff", ["rule_registry", "formatter_linter_pipeline", "performance_architecture", "compatibility_layer"]],
  ["pnpm/pnpm", ["content_addressable_store", "workspace", "dependency_graph", "monorepo_architecture"]],
  ["microsoft/playwright", ["browser_automation_abstraction", "fixture", "runner", "cross_browser_adapter"]],
  ["curl/curl", ["protocol_adapter", "portable_cli", "transfer_state_machine", "compatibility_boundary"]],
  ["nodejs/node", ["runtime_boundary", "event_loop", "module_loading", "compatibility_governance"]],
  ["redis/redis", ["command_table", "server_runtime", "persistence", "replication"]],
  ["apache/airflow", ["dag_scheduling", "operator_abstraction", "executor_boundary", "workflow_observability"]],
  ["dbt-labs/dbt-core", ["declarative_config", "adapter_pattern", "sql_model_graph", "compile_run_boundary"]],
  ["nats-io/nats-server", ["pub_sub_core", "cluster_protocol", "subject_routing", "server_runtime_boundary"]],
  ["etcd-io/etcd", ["distributed_kv", "consensus_boundary", "watch_api", "lease_session_model"]],
  ["ClickHouse/ClickHouse", ["query_engine", "storage_engine", "pipeline_execution", "test_ci_discipline"]],
  ["denoland/deno", ["permission_model", "module_loading", "cli_runtime_boundary", "standard_tooling"]],
  ["oven-sh/bun", ["integrated_runtime", "test_runner", "bundler", "package_manager_integration"]],
  ["biomejs/biome", ["unified_toolchain", "formatter_linter_lsp_boundary", "rule_system"]],
  ["eslint/eslint", ["rule_plugin_system", "config_evolution", "ast_pipeline", "ecosystem_compatibility"]],
  ["prettier/prettier", ["printer_architecture", "language_plugin", "opinionated_api_boundary"]],
  ["vitest-dev/vitest", ["test_runner", "watch_mode", "vite_integration", "mocking_boundary"]],
  ["cypress-io/cypress", ["browser_testing_architecture", "runner_app_split", "debuggability"]],
  ["storybookjs/storybook", ["component_workshop", "addon_system", "preview_manager_split", "docs_pipeline"]],
  ["BurntSushi/ripgrep", ["high_performance_cli", "ignore_rules", "streaming_search", "cross_platform_design"]],
  ["sharkdp/bat", ["cli_ux", "syntax_highlighting_adapter", "configuration", "theme_system"]],
  ["nushell/nushell", ["typed_pipeline", "command_model", "plugin_extension", "structured_data_flow"]],
  ["cli/cli", ["command_routing", "github_api_adapter", "auth_flow", "terminal_ux"]],
  ["docker/compose", ["declarative_config", "service_graph", "docker_adapter", "local_orchestration"]],
  ["opentofu/opentofu", ["declarative_infra", "state_management", "provider_system", "plan_apply_workflow"]],
  ["moby/moby", ["container_runtime", "daemon_client_boundary", "subsystem_boundary"]],
  ["jaegertracing/jaeger", ["tracing_pipeline", "storage_adapter", "collector_query_frontend_split"]],
  ["minio/minio", ["s3_api_boundary", "distributed_storage", "erasure_coding", "admin_surface"]],
  ["duckdb/duckdb", ["embedded_database", "query_execution", "extension_system", "single_process_architecture"]],
  ["valkey-io/valkey", ["cache_server", "command_table", "replication", "compatibility_governance"]],
  ["supabase/supabase", ["postgres_platform", "monorepo", "service_integration", "dx_layer"]],
  ["vercel/next.js", ["routing", "server_client_boundary", "build_pipeline", "cache_revalidate_model"]],
  ["react/react", ["reconciler", "component_model", "scheduler", "api_stability"]],
  ["vuejs/core", ["reactivity_system", "compiler_runtime_split", "composition_api_boundary"]],
  ["sveltejs/svelte", ["compiler_first_framework", "reactivity_transform", "runtime_minimization"]],
  ["withastro/astro", ["island_architecture", "content_collections", "integration_system", "build_runtime_split"]],
  ["tailwindlabs/tailwindcss", ["config_driven_compiler", "utility_generation", "plugin_api", "dx_tradeoff"]],
  ["honojs/hono", ["web_standards_api", "middleware", "edge_runtime_portability"]],
  ["nestjs/nest", ["dependency_injection", "module_system", "decorator_metadata", "enterprise_backend_structure"]],
  ["trpc/trpc", ["type_safe_api", "router_composition", "client_server_contract"]],
  ["django/django", ["batteries_included_architecture", "orm_admin_auth_migrations", "stable_conventions"]],
  ["fastapi/fastapi", ["type_driven_api", "schema_generation", "dependency_injection", "validation_boundary"]],
  ["pallets/flask", ["minimal_core", "extension_ecosystem", "request_app_context", "small_framework_boundary"]],
  ["hashicorp/vault", ["security_boundary", "secret_engine", "policy_system", "plugin_backend"]],
  ["envoyproxy/envoy", ["proxy_filter_chain", "xds_control_plane", "observability_boundary", "runtime_config"]],
  ["getsentry/sentry", ["error_ingestion", "event_pipeline", "product_platform_boundary", "observability_workflow"]],
  ["ollama/ollama", ["local_model_server", "model_packaging", "cli_api_boundary", "runtime_ux"]],
  ["vllm-project/vllm", ["inference_serving", "scheduler", "memory_management", "throughput_engine"]],
  ["huggingface/transformers", ["model_registry", "pipeline_api", "backend_abstraction", "compatibility_management"]],
  ["ray-project/ray", ["distributed_task_runtime", "actor_model", "scheduler", "ai_workload_orchestration"]],
  ["elastic/elasticsearch", ["distributed_search", "cluster_state", "query_engine", "index_storage_boundary"]]
];

export const DEFAULT_SEED_REPOS: SeedRepo[] = rows.map(([repo, focus], index) => ({
  rank: index + 1,
  repo,
  url: `https://github.com/${repo}`,
  priority: index < 20 ? "p1" : index < 40 ? "p2" : "p3",
  focus
}));
